version: "3.1"
services:
  app:
    build: 
      context: .
      dockerfile: compose/node/Dockerfile
    image: "lazamini_fe"
    container_name: "lazamini_fe_container"
    working_dir: /lazamini_fe
    volumes: 
      - ./:/lazamini_fe
    ports: 
      - "5000:80"
    command: "npm run start"

  lazamini_webserver:
    build: 
      context: compose/nginx/
    image: "lazamini_fe_webserver"
    volumes: 
      - ./:/lazamini_fe
    ports: 
      - "6000:80"